{/* <p> OUMESSAOUD Azzedine: oumessaoud@hotmail.fr</p>  */}

const candidates = [
  {
    name: "John Doe",
    username: "john.doe",
    email: "john@example.com",
    phone: "123-456-7890",
    poste: "Développeur Web",
    offres_d_emploi: "Développeur Front-end",
    ville: "New York",
  },
  {
    name: "Jane Smith",
    username: "jane.smith",
    email: "jane@example.com",
    phone: "987-654-3210",
    poste: "Ingénieur Logiciel",
    offres_d_emploi: "Ingénieur Backend",
    ville: "New York",
  },
  {
    name: "Alice Johnson",
    username: "alice.johnson",
    email: "alice@example.com",
    phone: "555-555-5555",
    poste: "Designer UI/UX",
    offres_d_emploi: "Designer Graphique",
    ville: "New York",
  },
  {
    name: "Bob Williams",
    username: "bob.williams",
    email: "bob@example.com",
    phone: "777-777-7777",
    poste: "Développeur Web",
    offres_d_emploi: "Chef de Projet Senior",
    ville: "Chicago",
  },
  {
    name: "Eva Davis",
    username: "eva.davis",
    email: "eva@example.com",
    phone: "444-444-4444",
    poste: "Développeur Web",
    offres_d_emploi: "Analyste de Données Junior",
    ville: "Miami",
  },
  {
    name: "Michael Brown",
    username: "michael.brown",
    email: "michael@example.com",
    phone: "888-888-8888",
    poste: "Développeur Full Stack",
    offres_d_emploi: "Développeur Back-end",
    ville: "Seattle",
  },
  {
    name: "Olivia Wilson",
    username: "olivia.wilson",
    email: "olivia@example.com",
    phone: "111-111-1111",
    poste: "Développeur Web",
    offres_d_emploi: "Ingénieur en Sécurité Senior",
    ville: "New York",
  },
  {
    name: "David Lee",
    username: "david.lee",
    email: "david@example.com",
    phone: "999-999-9999",
    poste: "Développeur Mobile",
    offres_d_emploi: "Développeur iOS",
    ville: "Austin",
  },
  {
    name: "Sophia Adams",
    username: "sophia.adams",
    email: "sophia@example.com",
    phone: "222-222-2222",
    poste: "Analyste Financier",
    offres_d_emploi: "Analyste Financier Junior",
    ville: "New York",
  },
  {
    name: "Matthew Taylor",
    username: "matthew.taylor",
    email: "matthew@example.com",
    phone: "333-333-3333",
    poste: "Développeur Web",
    offres_d_emploi: "Spécialiste Marketing",
    ville: "New York",
  },
];

export default candidates;
