const Offres = [
  {
    Poste: "Développeur Web",
    Ville: "Paris",
    Type_de_contrat: "CDI",
    Duree_de_contrat: "Indéterminée",
    Horaires: "Temps plein",
    Experience: "2 ans",
    Salaire: "50000 EUR par an",
    Politique_teletravail: "Partiel",
    Type_de_competence: "Informatique",
    Competence: "HTML, CSS, JavaScript, React, Node.js"
  },
  {
    Poste: "Assistant Marketing",
    Ville: "Lyon",
    Type_de_contrat: "CDD",
    Duree_de_contrat: "6 mois",
    Horaires: "Temps partiel",
    Experience: "1 an",
    Salaire: "30000 EUR par an",
    Politique_teletravail: "Aucun",
    Type_de_competence: "Marketing",
    Competence: "Stratégie marketing, Analyse de marché, Réseaux sociaux"
  },
  {
    Poste: "Ingénieur en Informatique",
    Ville: "Marseille",
    Type_de_contrat: "CDI",
    Duree_de_contrat: "Indéterminée",
    Horaires: "Temps plein",
    Experience: "3 ans",
    Salaire: "60000 EUR par an",
    Politique_teletravail: "Flexible",
    Type_de_competence: "Informatique",
    Competence: "Java, Python, C++, Développement logiciel"
  },
  {
    Poste: "Designer Graphique",
    Ville: "Bordeaux",
    Type_de_contrat: "CDI",
    Duree_de_contrat: "Indéterminée",
    Horaires: "Temps plein",
    Experience: "2 ans",
    Salaire: "45000 EUR par an",
    Politique_teletravail: "Partiel",
    Type_de_competence: "Design",
    Competence: "Adobe Creative Suite, Conception graphique, Illustration"
  },
  {
    Poste: "Assistant Administratif",
    Ville: "Toulouse",
    Type_de_contrat: "CDD",
    Duree_de_contrat: "6 mois",
    Horaires: "Temps plein",
    Experience: "1 an",
    Salaire: "32000 EUR par an",
    Politique_teletravail: "Aucun",
    Type_de_competence: "Administration",
    Competence: "Gestion de dossiers, Microsoft Office, Communication"
  },
  {
    Poste: "Chef de Projet IT",
    Ville: "Nantes",
    Type_de_contrat: "CDI",
    Duree_de_contrat: "Indéterminée",
    Horaires: "Temps plein",
    Experience: "4 ans",
    Salaire: "70000 EUR par an",
    Politique_teletravail: "Flexible",
    Type_de_competence: "Informatique",
    Competence: "Gestion de projet, Leadership, Développement logiciel"
  },
  {
    Poste: "Infirmière",
    Ville: "Lille",
    Type_de_contrat: "CDI",
    Duree_de_contrat: "Indéterminée",
    Horaires: "Temps partiel",
    Experience: "3 ans",
    Salaire: "38000 EUR par an",
    Politique_teletravail: "Aucun",
    Type_de_competence: "Santé",
    Competence: "Soins infirmiers, Gestion des patients, Santé publique"
  },
  {
    Poste: "Commercial",
    Ville: "Strasbourg",
    Type_de_contrat: "CDI",
    Duree_de_contrat: "Indéterminée",
    Horaires: "Temps plein",
    Experience: "2 ans",
    Salaire: "55000 EUR par an",
    Politique_teletravail: "Partiel",
    Type_de_competence: "Ventes",
    Competence: "Négociation, Prospection, Service client"
  },
  {
    Poste: "Enseignant",
    Ville: "Rennes",
    Type_de_contrat: "CDI",
    Duree_de_contrat: "Indéterminée",
    Horaires: "Temps plein",
    Experience: "5 ans",
    Salaire: "48000 EUR par an",
    Politique_teletravail: "Flexible",
    Type_de_competence: "Éducation",
    Competence: "Pédagogie, Gestion de classe, Matières enseignées"
  },
  {
    Poste: "Analyste Financier",
    Ville: "Nice",
    Type_de_contrat: "CDI",
    Duree_de_contrat: "Indéterminée",
    Horaires: "Temps plein",
    Experience: "3 ans",
    Salaire: "65000 EUR par an",
    Politique_teletravail: "Partiel",
    Type_de_competence: "Finance",
    Competence: "Analyse financière, Modélisation, Rapports financiers"
  },
  {
    Poste: "Chirurgien",
    Ville: "Marseille",
    Type_de_contrat: "CDI",
    Duree_de_contrat: "Indéterminée",
    Horaires: "Temps plein",
    Experience: "8 ans",
    Salaire: "90000 EUR par an",
    Politique_teletravail: "Aucun",
    Type_de_competence: "Santé",
    Competence: "Chirurgie générale, Anesthésie, Soins post-opératoires"
  },
  {
    Poste: "Architecte",
    Ville: "Bordeaux",
    Type_de_contrat: "CDI",
    Duree_de_contrat: "Indéterminée",
    Horaires: "Temps plein",
    Experience: "5 ans",
    Salaire: "75000 EUR par an",
    Politique_teletravail: "Partiel",
    Type_de_competence: "Architecture",
    Competence: "Conception architecturale, Dessins techniques, Réglementations de construction"
  },
  {
    Poste: "Psychologue Clinicien",
    Ville: "Lyon",
    Type_de_contrat: "CDI",
    Duree_de_contrat: "Indéterminée",
    Horaires: "Temps partiel",
    Experience: "6 ans",
    Salaire: "60000 EUR par an",
    Politique_teletravail: "Aucun",
    Type_de_competence: "Psychologie",
    Competence: "Thérapie individuelle, Évaluation psychologique, Conseil en santé mentale"
  },
  {
    Poste: "Électricien",
    Ville: "Paris",
    Type_de_contrat: "CDI",
    Duree_de_contrat: "Indéterminée",
    Horaires: "Temps plein",
    Experience: "4 ans",
    Salaire: "45000 EUR par an",
    Politique_teletravail: "Aucun",
    Type_de_competence: "Électricité",
    Competence: "Installation électrique, Dépannage, Maintenance électrique"
  },
  // ... Ajoutez d'autres offres ici ...
];

export default Offres;
