{/* <p> OUMESSAOUD Azzedine: oumessaoud@hotmail.fr</p>  */}

const Societe = [
    {
      nom_de_lentreprise: 'Société 1',
      secteur_activite: 'Secteur 1',
      raison_sociale: 'Raison Sociale 1',
      statut_juridique: 'Statut Juridique 1',
      telephone: '1234567890',
      adresse: 'Adresse 1',
      effectif: '50',
      mail: 'societe1@example.com',
      site_web: 'https://www.societe1.com',
      reseaux_sociaux: 'Facebook, Twitter, LinkedIn',
      code_NAF_principal: '12345',
      politique_teletravail: 'Oui',
    },
    {
      nom_de_lentreprise: 'Société 2',
      secteur_activite: 'Secteur 2',
      raison_sociale: 'Raison Sociale 2',
      statut_juridique: 'Statut Juridique 2',
      telephone: '9876543210',
      adresse: 'Adresse 2',
      effectif: '100',
      mail: 'societe2@example.com',
      site_web: 'https://www.societe2.com',
      reseaux_sociaux: 'Facebook, Twitter',
      code_NAF_principal: '54321',
      politique_teletravail: 'Non',
    },
    {
      nom_de_lentreprise: 'Société 3',
      secteur_activite: 'Secteur 3',
      raison_sociale: 'Raison Sociale 3',
      statut_juridique: 'Statut Juridique 3',
      telephone: '5555555555',
      adresse: 'Adresse 3',
      effectif: '200',
      mail: 'societe3@example.com',
      site_web: 'https://www.societe3.com',
      reseaux_sociaux: 'LinkedIn, Instagram',
      code_NAF_principal: '67890',
      politique_teletravail: 'Oui',
    },
    {
      nom_de_lentreprise: 'Société 4',
      secteur_activite: 'Secteur 4',
      raison_sociale: 'Raison Sociale 4',
      statut_juridique: 'Statut Juridique 4',
      telephone: '1111111111',
      adresse: 'Adresse 4',
      effectif: '75',
      mail: 'societe4@example.com',
      site_web: 'https://www.societe4.com',
      reseaux_sociaux: 'Twitter, LinkedIn',
      code_NAF_principal: '45678',
      politique_teletravail: 'Non',
    },
    {
      nom_de_lentreprise: 'Société 5',
      secteur_activite: 'Secteur 5',
      raison_sociale: 'Raison Sociale 5',
      statut_juridique: 'Statut Juridique 5',
      telephone: '2222222222',
      adresse: 'Adresse 5',
      effectif: '300',
      mail: 'societe5@example.com',
      site_web: 'https://www.societe5.com',
      reseaux_sociaux: 'Facebook, Instagram',
      code_NAF_principal: '98765',
      politique_teletravail: 'Oui',
    },
    {
      nom_de_lentreprise: 'Société 6',
      secteur_activite: 'Secteur 6',
      raison_sociale: 'Raison Sociale 6',
      statut_juridique: 'Statut Juridique 6',
      telephone: '3333333333',
      adresse: 'Adresse 6',
      effectif: '50',
      mail: 'societe6@example.com',
      site_web: 'https://www.societe6.com',
      reseaux_sociaux: 'LinkedIn, Twitter, Instagram',
      code_NAF_principal: '23456',
      politique_teletravail: 'Oui',
    },
    {
      nom_de_lentreprise: 'Société 7',
      secteur_activite: 'Secteur 7',
      raison_sociale: 'Raison Sociale 7',
      statut_juridique: 'Statut Juridique 7',
      telephone: '4444444444',
      adresse: 'Adresse 7',
      effectif: '150',
      mail: 'societe7@example.com',
      site_web: 'https://www.societe7.com',
      reseaux_sociaux: 'Facebook, Twitter, LinkedIn',
      code_NAF_principal: '87654',
      politique_teletravail: 'Oui',
    },
    {
      nom_de_lentreprise: 'Société 8',
      secteur_activite: 'Secteur 8',
      raison_sociale: 'Raison Sociale 8',
      statut_juridique: 'Statut Juridique 8',
      telephone: '5555555555',
      adresse: 'Adresse 8',
      effectif: '250',
      mail: 'societe8@example.com',
      site_web: 'https://www.societe8.com',
      reseaux_sociaux: 'Instagram, Twitter',
      code_NAF_principal: '54321',
      politique_teletravail: 'Oui',
    },
    {
      nom_de_lentreprise: 'Société 9',
      secteur_activite: 'Secteur 9',
      raison_sociale: 'Raison Sociale 9',
      statut_juridique: 'Statut Juridique 9',
      telephone: '6666666666',
      adresse: 'Adresse 9',
      effectif: '80',
      mail: 'societe9@example.com',
      site_web: 'https://www.societe9.com',
      reseaux_sociaux: 'Facebook, Instagram, LinkedIn',
      code_NAF_principal: '98765',
      politique_teletravail: 'Non',
    },
    {
      nom_de_lentreprise: 'Société 10',
      secteur_activite: 'Secteur 10',
      raison_sociale: 'Raison Sociale 10',
      statut_juridique: 'Statut Juridique 10',
      telephone: '7777777777',
      adresse: 'Adresse 10',
      effectif: '120',
      mail: 'societe10@example.com',
      site_web: 'https://www.societe10.com',
      reseaux_sociaux: 'Twitter, Instagram',
      code_NAF_principal: '23456',
      politique_teletravail: 'Oui',
    },
  ];
  
  export default Societe;
  