const users = [
  {
    civilite: 'Monsieur',
    nom: 'Dupont',
    prenom: 'Jean',
    numero_telephone: '1234567890',
    email: 'jean.dupont@example.com',
    mot_de_passe: 'motdepasse1',
    poste_recherche: 'Ingénieur en informatique',
    experience: '5 ans',
    mobilite_geographique: 'Nationale',
    role: 'recruteur',
    competence: 'HTML',
    type_de_competence: 'Informatique',
  },
  {
    civilite: 'Madame',
    nom: 'Martin',
    prenom: 'Sophie',
    numero_telephone: '9876543210',
    email: 'sophie.martin@example.com',
    mot_de_passe: 'motdepasse2',
    poste_recherche: 'Développeur Web',
    experience: '3 ans',
    mobilite_geographique: 'Régionale',
    role: 'candidat',
    competence: "HTML, CSS, JavaScript, React, Node.js, Java",
    type_de_competence: "Informatique",
  },
  {
    civilite: 'Monsieur',
    nom: 'Tremblay',
    prenom: 'Michel',
    numero_telephone: '5551234567',
    email: 'michel.tremblay@example.com',
    mot_de_passe: 'motdepasse3',
    poste_recherche: 'Chef de projet',
    experience: '8 ans',
    mobilite_geographique: 'Internationale',
    role: 'admin',
    competence: 'Java',
    type_de_competence: 'Informatique',
  },
  {
    civilite: 'Madame',
    nom: 'Lefebvre',
    prenom: 'Marie',
    numero_telephone: '4449876543',
    email: 'marie.lefebvre@example.com',
    mot_de_passe: 'motdepasse4',
    poste_recherche: 'Designer graphique',
    experience: '4 ans',
    mobilite_geographique: 'Nationale',
    role: 'recruteur',
    competence: 'Adobe Creative Suite',
    type_de_competence: 'Design',
  },
  {
    civilite: 'Monsieur',
    nom: 'Garcia',
    prenom: 'Carlos',
    numero_telephone: '7775554444',
    email: 'carlos.garcia@example.com',
    mot_de_passe: 'motdepasse5',
    poste_recherche: 'Développeur Full Stack',
    experience: '6 ans',
    mobilite_geographique: 'Régionale',
    role: 'candidat',
    competence: "HTML, CSS, JavaScript",
    type_de_competence: "Informatique",
  },
  {
    civilite: 'Monsieur',
    nom: 'Smith',
    prenom: 'John',
    numero_telephone: '1231231234',
    email: 'john.smith@example.com',
    mot_de_passe: 'motdepasse6',
    poste_recherche: 'Ingénieur mécanique',
    experience: '7 ans',
    mobilite_geographique: 'Nationale',
    role: 'candidat',
    competence: 'Gestion de projet',
    type_de_competence: 'Informatique',
  },
  {
    civilite: 'Madame',
    nom: 'Wang',
    prenom: 'Li',
    numero_telephone: '9998887777',
    email: 'li.wang@example.com',
    mot_de_passe: 'motdepasse7',
    poste_recherche: 'Analyste financier',
    experience: '2 ans',
    mobilite_geographique: 'Internationale',
    role: 'candidat',
    competence: 'Soins infirmiers',
    type_de_competence: 'Santé',
  },
  {
    civilite: 'Monsieur',
    nom: 'Chen',
    prenom: 'Wei',
    numero_telephone: '5554443333',
    email: 'wei.chen@example.com',
    mot_de_passe: 'motdepasse8',
    poste_recherche: 'Data Scientist',
    experience: '4 ans',
    mobilite_geographique: 'Régionale',
    role: 'candidat',
    competence: 'Négociation',
    type_de_competence: 'Ventes',
  },
  {
    civilite: 'Monsieur',
    nom: 'Johnson',
    prenom: 'Robert',
    numero_telephone: '7776665555',
    email: 'robert.johnson@example.com',
    mot_de_passe: 'motdepasse9',
    poste_recherche: 'Avocat',
    experience: '9 ans',
    mobilite_geographique: 'Nationale',
    role: 'candidat',
    competence: 'Droit des sociétés',
    type_de_competence: 'Droit',
  },
  {
    civilite: 'Madame',
    nom: 'Kim',
    prenom: 'Eunji',
    numero_telephone: '1112223333',
    email: 'eunji.kim@example.com',
    mot_de_passe: 'motdepasse10',
    poste_recherche: 'Développeur Mobile',
    experience: '3 ans',
    mobilite_geographique: 'Régionale',
    role: 'recruteur',
    competence: 'Swift',
    type_de_competence: 'Informatique',
  },
];

export default users;
